/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py BTCUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py ETHUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py BNBUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py SOLUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py LTCUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py DOGEUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py XRPUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py LINKUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py OPUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py AVAXUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py BCHUSDT 1h
/Users/longquan/anaconda3/envs/Kronos/bin/python /Users/longquan/Documents/git/py/kronos/src/btcusdt_kline_once_time.py UNIUSDT 1h